In [6]:
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium import webdriver
import time
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException, TimeoutException, WebDriverException
import logging
from seleniumbase import Driver
import pandas as pd

In [10]:
team_links = {
    "Islamabad United": "https://www.espncricinfo.com/records/trophy/averages-batting/pakistan-super-league-205?team=5795",
    "Karachi Kings": "https://www.espncricinfo.com/records/trophy/averages-batting/pakistan-super-league-205?team=5793",
    "Lahore Qalandars": "https://www.espncricinfo.com/records/trophy/averages-batting/pakistan-super-league-205?team=5799",
    "Multan Sultans": "https://www.espncricinfo.com/records/trophy/averages-batting/pakistan-super-league-205?team=6413",
    "Peshawar Zalmi": "https://www.espncricinfo.com/records/trophy/averages-batting/pakistan-super-league-205?team=5791",
    "Quetta Gladiators": "https://www.espncricinfo.com/records/trophy/averages-batting/pakistan-super-league-205?team=5797"
}

In [11]:
all_team_data = []

for team, link in team_links.items():
    driver.get(link)
    table = driver.find_element(By.XPATH, '//table[1]')
    rows = table.find_elements(By.TAG_NAME, 'tr')
    team_data = []
    
    for row in rows[1:]:
        cells = row.find_elements(By.TAG_NAME, "td")
        if len(cells) > 0:
            row_data = {
                "Team": team,
                "Player": cells[0].text,
                "Span": cells[1].text,
                "Mat": cells[2].text,
                "Inns": cells[3].text,
                "NO": cells[4].text,
                "Runs": cells[5].text,
                "HS": cells[6].text,
                "Ave": cells[7].text,
                "SR": cells[8].text,
                "100": cells[9].text,
                "50": cells[10].text,
                "0": cells[11].text
            }
            team_data.append(row_data)
    
    all_team_data.extend(team_data)

In [12]:
batting_df = pd.DataFrame(all_team_data)
batting_df

,Team,Player,Span,Mat,Inns,NO,Runs,HS,Ave,SR,100,50,0
0,Islamabad United,Abrar Ahmed,2023-2023,3,2,-,-,-,0.00,0.00,-,-,2
1,Islamabad United,Agha Salman,2024-2024,12,12,2,310,64*,31.00,140.27,-,2,-
2,Islamabad United,Ahmed Safi Abdullah,2020-2020,3,2,2,9,8*,0.00,69.23,-,-,-
3,Islamabad United,Akif Javed,2020-2021,11,3,3,-,0*,0.00,0.00,-,-,-
4,Islamabad United,Ali Khan,2021-2021,3,-,-,-,-,0.00,0.00,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,Quetta Gladiators,Yasir Khan,2023-2023,2,2,-,19,14,9.50,73.07,-,-,-
577,Quetta Gladiators,Zahid Mahmood,2020-2021,7,5,2,24,19*,8.00,80.00,-,-,2
578,Quetta Gladiators,Zahir Khan,2021-2021,2,2,1,12,6*,12.00,150.00,-,-,-
579,Quetta Gladiators,Zahoor Khan,2021-2021,1,-,-,-,-,0.00,0.00,-,-,-
580,Quetta Gladiators,Zulfiqar Babar,2016-2017,18,6,3,23,20*,7.66,135.29,-,-,2

In [13]:
batting_df.to_csv('PSL_Batting_Dataset.csv')

In [14]:
team_links_bowling = {
    "Islamabad United": "https://www.espncricinfo.com/records/trophy/averages-bowling/pakistan-super-league-205?team=5795",
    "Karachi Kings": "https://www.espncricinfo.com/records/trophy/averages-bowling/pakistan-super-league-205?team=5793",
    "Lahore Qalandars": "https://www.espncricinfo.com/records/trophy/averages-bowling/pakistan-super-league-205?team=5799",
    "Multan Sultans": "https://www.espncricinfo.com/records/trophy/averages-bowling/pakistan-super-league-205?team=6413",
    "Peshawar Zalmi": "https://www.espncricinfo.com/records/trophy/averages-bowling/pakistan-super-league-205?team=5791",
    "Quetta Gladiators": "https://www.espncricinfo.com/records/trophy/averages-bowling/pakistan-super-league-205?team=5797"
}

In [15]:
all_team_bowling_data = []

for team, link in team_links_bowling.items():
    driver.get(link)
    table = driver.find_element(By.XPATH, '//table[1]')
    rows = table.find_elements(By.TAG_NAME, 'tr')
    team_data = []
    
    for row in rows[1:]:
        cells = row.find_elements(By.TAG_NAME, "td")
        if len(cells) > 0:
            row_data = {
                "Team": team,
                "Player": cells[0].text,
                "Span": cells[1].text,
                "Mat": cells[2].text,
                "Inns": cells[3].text,
                "Balls": cells[4].text,
                "Mdns": cells[5].text,
                "Runs": cells[6].text,
                "Wkts": cells[7].text,
                "BBI": cells[8].text,
                "Ave": cells[9].text,
                "Econ": cells[10].text,
                "SR": cells[11].text,
                "5": cells[12].text,
                "10": cells[13].text,
                "Ct": cells[14].text,
                "St": cells[15].text,
                
            }
            team_data.append(row_data)
    
    all_team_bowling_data.extend(team_data)

In [16]:
bowling_df = pd.DataFrame(all_team_bowling_data)
bowling_df

,Team,Player,Span,Mat,Inns,Balls,Mdns,Runs,Wkts,BBI,Ave,Econ,SR,5,10,Ct,St
0,Islamabad United,Abrar Ahmed,2023-2023,3,3,72,-,92,3,2/21,30.66,7.66,24.0,-,-,-,-
1,Islamabad United,Agha Salman,2024-2024,12,5,72,-,97,2,1/17,48.50,8.08,36.0,-,-,1,-
2,Islamabad United,Ahmed Safi Abdullah,2020-2020,3,3,48,-,65,4,2/17,16.25,8.12,12.0,-,-,-,-
3,Islamabad United,Akif Javed,2020-2021,11,10,204,-,285,10,3/43,28.50,8.38,20.4,-,-,2,-
4,Islamabad United,Ali Khan,2021-2021,3,3,50,-,70,2,1/10,35.00,8.40,25.0,-,-,1,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
576,Quetta Gladiators,Yasir Khan,2023-2023,2,-,0,-,-,-,-,0.00,-,-,-,-,2,-
577,Quetta Gladiators,Zahid Mahmood,2020-2021,7,7,137,-,243,6,2/29,40.50,10.64,22.8,-,-,-,-
578,Quetta Gladiators,Zahir Khan,2021-2021,2,2,48,-,56,1,1/25,56.00,7.00,48.0,-,-,1,-
579,Quetta Gladiators,Zahoor Khan,2021-2021,1,1,6,-,23,-,-,0.00,23.00,-,-,-,-,-
580,Quetta Gladiators,Zulfiqar Babar,2016-2017,18,18,432,2,499,15,2/17,33.26,6.93,28.8,-,-,7,-

In [17]:
bowling_df.to_csv('PSL_Bowling_Dataset.csv')